dist: trusty

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

addons:
  apt:
    packages:
      - python-dev
      - python3-dev

before_install:
  - pip install -r requirements.txt

install:
  - pip install .

script:
  - cd tests/ && py.test test_cgnswrap.py
